# Generated by Django 5.0.7 on 2024-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_fotografia_legenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caricaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
