# Generated by Django 5.0.7 on 2024-08-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_caricaturas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caricaturas',
            new_name='Caricatura',
        ),
    ]
