# Generated by Django 5.0.7 on 2024-08-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_rename_caricaturas_caricatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='caricatura',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
