# Generated by Django 5.0.7 on 2024-08-07 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_caricatura_publicada_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='caricatura',
            name='data_Imagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
