# Generated by Django 5.0.7 on 2024-08-07 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_caricatura_data_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_Imagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
