# Generated by Django 5.0.7 on 2024-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_data_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caricatura',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/caricaturas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/projetos/%Y/%m/%d'),
        ),
    ]
